### ISSUE TITLE
Replant duplication problem

### ISSUE THREAD

**Issue by Bucketsmith** [nivoridocs/strawgolem#6]
In R.A.D., using Mystical Agricraft. I don't know how relevant this is, but supplying that info anyway.

The straw golems replant, but they also drop the seed. This means they effectively duplicate the seed, in a cheating way.

Is it a known bug? Is it known why it does it?
Can it be fixed?

**Comment by un-nubivago** [comment]
Yes, it's kinda supposed to happen. And I'll not going to change it since it will be complicated to write code that edits the drop of every possible plant just to reduce the number of dropped seeds by one (more complicated the code is, more error-prone it will be, and I like to keep things simple).
If you can, you may reduce the drop chance of that seeds using other mods. Otherwise, you may just accept the extra seed as a gift given to you by your little golems 😄.

**Comment by Bucketsmith** [comment]
That's understandable, but unfortunate. I feel the extra seeds are cheaty and was hoping to use the straw golems in the R.A.D. modpack to automate farming.
I'm not sure there's another way to harvest and replant. :(
